export default {
  INIT_APP: 'INIT_APP',
  INIT_APP_OK: 'INIT_APP_OK',
  JSON_FILE_UPLOADED: 'JSON_FILE_UPLOADED',
  JSON_FILE_UPLOADED_SUCCESSFUL: 'JSON_FILE_UPLOADED_SUCCESSFUL',
  REMOVE_PERSON: 'REMOVE_PERSON',
  ADD_PERSON: 'ADD_PERSON',
  CHANGE_FILTER: 'CHANGE_FILTER',
  TOGGLE_COLLAPSE: 'TOGGLE_COLLAPSE',
  DETECT_MULTIPLE_BOSS: 'DETECT_MULTIPLE_BOSS',
  REMOVE_MULTIPLE_PERSON: 'REMOVE_MULTIPLE_PERSON',
  NOTIFICATION: 'NOTIFICATION',
  CHANGE_HIERARCHY: 'CHANGE_HIERARCHY',
};
